### ISSUE TITLE
Integration not working in Home Assistant OS 2026.7.0

### ISSUE THREAD

**Issue by mike4001** [callifo/fronius_modbus#115]
Just to make a seperate topic for the main release.

Fronius Modbus Integration cannot load on todays release of HAOS 2026.7.0

**Comment by robert-jonas-technikum-wien-at** [comment]
Same for me:
Log:
Setup failed for custom integration 'fronius_modbus': Unable to import component: cannot import name 'unpack_bitstring' from 'pymodbus.utilities' (/usr/local/lib/python3.14/site-packages/pymodbus/utilities.py) 
 07:13:06 – (FEHLER) setup.py
 Detected blocking call to import_module with args ('custom_components.fronius_modbus',) in /usr/src/homeassistant/homeassistant/loader.py, line 1091: ComponentProtocol, importlib.import_module(self.pkg_path) inside the event loop; This is causing stability issues. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#import_module Traceback (most recent call last): File "<frozen runpy>", line 203, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 227, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 213, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 289, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.14/asyncio/base_events.py", line 706, in run_until_complete self.run_forever() File "/usr/local/lib/python3.14/asyncio/base_events.py", line 677, in run_forever self._run_once() File "/usr/local/lib/python3.14/asyncio/base_events.py", line 2056, in _run_once handle._run() File "/usr/local/lib/python3.14/asyncio/events.py", line 94, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/setup.py", line 168, in async_setup_component result = await _async_setup_component(hass, domain, config) File "/usr/src/homeassistant/homeassistant/setup.py", line 341, in _async_setup_component component = await integration.async_get_component() File "/usr/src/homeassistant/homeassistant/loader.py", line 1043, in async_get_component comp = self._get_component() File "/usr/src/homeassistant/homeassistant/loader.py", line 1091, in _get_component ComponentProtocol, importlib.import_module(self.pkg_path) 
 07:13:06 – (WARNUNG) util/loop.py

**Comment by DerRheingold** [comment]
+1

**Comment by jan666** [comment]
I found the solution here:

https://github.com/binsentsu/home-assistant-solaredge-modbus/issues/372#issuecomment-4860605445

Line 15 in `extmodbusclient.py`

`    from pymodbus.pdu.utils import unpack_bitstring`

**Comment by mike4001** [comment]
I don't understand

Line 15 in `extmodbusclient.p`y reads

`from pymodbus.utilities import unpack_bitstring`

This is not the same as in the problem for the other integration.

**Comment by Andyt8** [comment]
> Line 15 in `extmodbusclient.py`
> 
> ` from pymodbus.pdu.utils import unpack_bitstring`


Yes, it seems to me, that fixed the problem for me too.


@mike4001 Exactly not the same problem in detail, but similar. It looks like the new pymodbus version use a new name for loading (importing features). It is true, the solaredge-modbus use different function, but the problem is, pymodbus.utilities changed to pymodbus.pdu.pdu and now to pymodbus.pdu.utils.


edit: correction for one mistake

**Comment by Andyt8** [comment]
By the way....

```
try:
    # For newer pymodbus versions (3.9.x+)
    from pymodbus.pdu.pdu import unpack_bitstring
except ImportError:
    # For older pymodbus versions (3.8.x and below)
    from pymodbus.pdu.utils import unpack_bitstring
```

...should be something like

```
try:
    # For newer pymodbus versions (3.13.x+)
    from pymodbus.pdu.utils import unpack_bitstring
except ImportError:
    # For newer pymodbus versions (3.9.x to 3.12.x)
    from pymodbus.pdu.pdu import unpack_bitstring
except ImportError:
    # For older pymodbus versions (3.8.x and below)
    from pymodbus.pdu.utils import unpack_bitstring
```

Don't know if my example will work, but with the newest version there will be three different names for the import.

**Comment by mike4001** [comment]
@Andyt8 

I see there is a new pull request which covers all HA versions. It´s basically what you wrote in your last post.

I have manually edited the file with the changes from there and it works again.

**Comment by DAVIZINH0** [comment]
> [@Andyt8](https://github.com/Andyt8)
> 
> I see there is a new pull request which covers all HA versions. It´s basically what you wrote in your last post.
> 
> I have manually edited the file with the changes from there and it works again.

i edited manually with the changes of the PR and working again.
thanks for all!

**Comment by elmocito** [comment]
Same problem here.

**Comment by jbvs01** [comment]
Solution worked for me as well.
To be edited in custom_compontents > fronius_modbus > extmodbusclient.py

> By the way....
> 
> ```
> try:
>     # For newer pymodbus versions (3.9.x+)
>     from pymodbus.pdu.pdu import unpack_bitstring
> except ImportError:
>     # For older pymodbus versions (3.8.x and below)
>     from pymodbus.pdu.utils import unpack_bitstring
> ```
> 
> ...should be something like
> 
> ```
> try:
>     # For newer pymodbus versions (3.13.x+)
>     from pymodbus.pdu.utils import unpack_bitstring
> except ImportError:
>     # For newer pymodbus versions (3.9.x to 3.12.x)
>     from pymodbus.pdu.pdu import unpack_bitstring
> except ImportError:
>     # For older pymodbus versions (3.8.x and below)
>     from pymodbus.pdu.utils import unpack_bitstring
> ```
> 
> Don't know if my example will work, but with the newest version there will be three different names for the import.

**Comment by elmocito** [comment]
This is solved with the last release. You can close this.

**Comment by mike4001** [comment]
> This is solved with the last release. You can close this.

There are 2 pull requests which fix this.

But there has not been a new release in 3 weeks.

As per now the issue still stands.

**Comment by elmocito** [comment]
Are we talking about the same integration?
https://github.com/binsentsu/home-assistant-solaredge-modbus

**Comment by mike4001** [comment]
> Are we talking about the same integration? https://github.com/binsentsu/home-assistant-solaredge-modbus

No :-)

This is the issue section for the Fronius Modbus integration.

**Comment by Ralf84** [comment]
> > Are we talking about the same integration? https://github.com/binsentsu/home-assistant-solaredge-modbus
> 
> No :-)
> 
> This is the issue section for the Fronius Modbus integration.

Yes still not working. They need to merge official the pull request.
I use the workaround above, till it's fixed

**Comment by Benjamin7785** [comment]
I used the quick fix successfully, too.

Line 15 in extmodbusclient.py reads
`from pymodbus.utilities import unpack_bitstring`

I then changed it to
`from pymodbus.pdu.utils import unpack_bitstring`

**Comment by callifo** [comment]
I've not been able to test the latest RC as I'm still on holidays for another 3 weeks. I can merge one of the two submitted PRs, if there is a consensus which is the more suitable/complete one? 

This one https://github.com/callifo/fronius_modbus/pull/118 looks well tested with previous and current version?

**Comment by mike4001** [comment]
> I've not been able to test the latest RC as I'm still on holidays for another 3 weeks. I can merge one of the two submitted PRs, if there is a consensus which is the more suitable/complete one?
> 
> This one [#118](https://github.com/callifo/fronius_modbus/pull/118) looks well tested with previous and current version?

Everyone here edited his files according to https://github.com/callifo/fronius_modbus/pull/116

https://github.com/callifo/fronius_modbus/pull/118 looks more "future-proof" and therefore "better" but at least in this Thread no one tested it.

So my suggestion would be to merge #116 for now and when you come back and find some time to test this to switch it out to #118

**Comment by callifo** [comment]
I've released 0.3.1-rc4 for testing.

**Comment by G-nn-r** [comment]
> I've released 0.3.1-rc4 for testing.

Works for me (at least it’s loading again and the momentary values look good, no extensive testing yet).

Thanks and enjoy your vacation! 🙂

Edit: Everything worked as expected in the past two weeks for me.

**Comment by mike4001** [comment]
Just one thing.

I noticed that after starting logs show a warning

`newer pymodbus 3.13.1 found`

But aside from this everything works perfectly.

**Comment by callifo** [comment]
I've updated the dependency to align to built in HA component version (3.13.1) in RC5.
